<a href="https://colab.research.google.com/github/vvicky30/python/blob/master/init_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [8]:
v= "vedantbhatt"
v.split("t")

['vedan', 'bha', '', '']

In [9]:
v.upper()

'VEDANTBHATT'

In [10]:
v.capitalize()

'Vedantbhatt'

In [13]:
v[::-1]#resverse

'ttahbtnadev'

In [14]:
v[2:4]#slicing

'da'

In [20]:
insects=['ant', 'cockroach','bee']
insects[len(insects):]='c'#without append-fn
insects

['ant', 'cockroach', 'bee', 'c']

In [0]:
t=("dgr",{"name":"n"})

In [23]:
t[1]["name"]

'n'

In [24]:

unit_tuple = "hello",
print(type(unit_tuple))  # <class 'tuple'>


<class 'tuple'>


In [27]:
l1=[1,2,3,4,5]
l2=[6,7,8,9]
d=list(zip(l1,l2))#with the help of zip we can iterate lopp on several datatypes in single innings
d

[(1, 6), (2, 7), (3, 8), (4, 9)]

In [25]:
v_letters = [ letter for letter in 'vedant' ]
print( v_letters)

['v', 'e', 'd', 'a', 'n', 't']


In [39]:
prime=[x for x in range(0, 100)
     if all(x % y != 0 for y in range(2, x))]
prime

[0,
 1,
 2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

In [45]:
b="v"
c="e"
v="d"
n="a"
if(b=="v" and c=="e" and v=="d" and n=="a"):
  print("you are right")

you are right


In [44]:
type(b)

str

In [65]:
#recursionprogram for the checking no. in the given list
def check(l):
  if len(l)==0:
    return False
  if l[0]==2:
    return True
  return check(l[1:])

ss=[1,24,5,6,7]
print(check(ss))


False


In [75]:
import numpy as np
l=[[1,2,3,4]]
a=np.array(l)
print(a)
print("a's dimention",a.shape)
l1=[l,l]
b=np.array(l1)
print(b)
print("b's dimention",b.shape)


[[1 2 3 4]]
a's dimention (1, 4)
[[[1 2 3 4]]

 [[1 2 3 4]]]
b's dimention (2, 1, 4)


In [86]:
l1=[1,2,3,4,5,6,7]   
l2=[l1,l1,l1,l1,l1,l1]
l3=[l2,l2,l2,l2,l2]
l4=[l3,l3]
l5=[l4,l4,l4]
b=np.array(l5)
print("b's shape",b.shape)
print("b's matrix",b)
print("b's size",b.size)


b's shape (3, 2, 5, 6, 7)
b's matrix [[[[[1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]]

   [[1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]]

   [[1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]]

   [[1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]]

   [[1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]]]


  [[[1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]]

   [[1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]
    [1 2 3 ... 5 6 7]]

   [[1 2 3 ... 5 6 7]
 